name: messenger
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  toastification: ^2.3.0
  lottie: ^3.1.0
  dotlottie_loader: ^0.0.5
  vibration: ^3.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/chat_backgrounds/
    - assets/animations/